# Generated by Django 6.0.2 on 2026-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('tech_stack', models.CharField(max_length=200)),
                ('total_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
