name: Django Backend CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django
          pip install -r requirements.txt || true

      - name: Django System Check
        run: |
          cd backend   # change this folder name to where manage.py exists
          python manage.py check
